### ISSUE TITLE
Couldn't create sourcemap

### ISSUE THREAD

**Issue by megachan** [benmccallum/AspNetBundling#10]
Hi,

First of all thank you for your wonderful work. 

I generated source map with latest version of AspNetBundling but it ended up creating the wrong source map file, for example 'xxxxxx.min.jsmap'

Kind regards,
Yui

**Comment by benmccallum** [comment]
Hi Yui, Are you able to give me some better reproduction steps? Thanks, Ben.

**Comment by megachan** [comment]
Hi Ben,

I have ScriptBundle like 
```
bundles.Add(new ScriptWithSourceMapBundle("~/Scripts/base.js").Include(
                "~/Scripts/a.js",
                "~/Scripts/b.js"
));
```

Then I ran without debugging mode and in base.js has the source map link 
`//# sourceMappingURL=/Scripts/base.jsmap`

Cheers,
Yui

**Comment by MSilvestroni** [comment]
It's the same for me!

**Comment by benmccallum** [comment]
So the problem here is that the file extension of the source map is wrong? Theoretically it shouldn't matter unless your server doesn't know how to handle that extension. Will have a quick look.

**Comment by benmccallum** [comment]
Hey guys, 

I had a closer look and realised what's going on here. In my latest release I don't actually ever write a .map file to the filesystem. Instead I use the same method of delivering virtual bundles as the framework does to serve a virtual bundle of the sourcemap. 

As long as you've got source maps enabled in your browser (e.g. under Settings in Dev Tools of Chrome), the browser will pick it up. 

Cheers,
Ben
