### ISSUE TITLE
CSS sourcemap support?

### ISSUE THREAD

**Issue by dieseltravis** [benmccallum/AspNetBundling#11]
Some sort of `StyleWithSourceMapBundle` class to include CSS sourcemaps would be nice.

**Comment by benmccallum** [comment]
Hey @dieseltravis , I remember I initially tried that in earlier versions but AjaxMin didn't seem to support it. At least, it wasn't generating anything.

**Comment by dieseltravis** [comment]
@benmccallum interesting, I'll take a look at AjaxMin and see if maybe a bug should be opened there.

**Comment by benmccallum** [comment]
Unfortunately AjaxMin doesn't seem to be very well supported. There's a few issues with it that everyone is working around. Let me know how you go though :)

**Comment by dieseltravis** [comment]
Ah yeah, I came across this open issue from 2014, doesn't sound very promising: 
https://ajaxmin.codeplex.com/workitem/21052

**Comment by benmccallum** [comment]
All I can say is swap to grunt or gulp and save yourself the heartache ;)
