### ISSUE TITLE
Huge Performance Issues

### ISSUE THREAD

**Issue by bugejakurt** [benmccallum/AspNetBundling#2]
I have found a number of performance issues:

1. For each bundle request AjaxMinBundleBuilder.BuildBundleContent writes to disk a .map file according to the contents in the bundle.
  - Appending a version querystring to the filename and comparing it with the bundle version querystring you can avoid from writing a new .map file to disk.
2. Can the builder attach to the bundle process at app_start? Then the map file generation will only happen at application initialisation not with every request.

**Comment by benmccallum** [comment]
I've had a look at this and as far as I can tell the BuildBundleContent method only ever gets called once on App_Start when the bundle contents needs to be generated. Only if the files change or the app pool recycles will this be called again.
