### ISSUE TITLE
CssRewriteUrlTransformFixed strips out quotes in url

### ISSUE THREAD

**Issue by mrbelk** [benmccallum/AspNetBundling#8]
I had some issues with embedded graphics in a background image.  Here is the CSS:

```css
background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='1'><rect fill='#c8c7cc' x='0' y='0' width='100%' height='0.5'/></svg>");
```

As you know, the ASP.NET bundling system wants to make the "data" part a relative URL and the image breaks.  I installed your Nuget and, while it corrects that behavior, it also seems to strip the containing quotes inside the "url" value and the image can't be rendered.

According to Chrome's inspector, the CSS looks like this:

```css
background-image: url(data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100%' height='1'><rect fill='#c8c7cc' x='0' y='0' width='100%' height='0.5'/></svg>);
```

I think it must be something in your regex match/replace.

Thanks,
Matthew

**Comment by benmccallum** [comment]
Hi @mrbelk, If you disable minification, by setting <compilation debug="false" /> in your web.config, do the surrounding quotes remain? Just wondering if it's the minifier which could be getting rid of quotes thinking they aren't required, because usually they aren't.

**Comment by mrbelk** [comment]
Well, it doesn’t do it when I am debugging; let me try setting that property on the BundleTable class in global.asax.cs on my “release” test site.

Thanks,
Matthew
________________________
Matthew Belk
ph. 678-287-3315

From: Ben McCallum
Reply-To: benmccallum/AspNetBundling
Date: Monday, July 27, 2015 at 9:40 AM
To: benmccallum/AspNetBundling
Cc: Matthew Belk
Subject: Re: [AspNetBundling] CssRewriteUrlTransformFixed strips out quotes in url (#8)


Hi @mrbelk<https://github.com/mrbelk>, If you disable minification, by setting in your web.config, do the surrounding quotes remain? Just wondering if it's the minifier which could be getting rid of quotes thinking they aren't required, because usually they aren't.

**Comment by mrbelk** [comment]
well, that's awesome.  When I set 

```csharp
BundleTable.EnableOptimizations = true;
```
in global.asax.cs, everything works right.  clearly this is non-optimal, though.

**Comment by benmccallum** [comment]
It's okay, I just need to adjust the regex like you mentioned. Working on a fix now.

**Comment by mrbelk** [comment]
awesome. thanks. will you update the nuget package fairly quickly?

**Comment by benmccallum** [comment]
Give it a quick second but it's up now, v2.0.2:
https://www.nuget.org/packages/AspNetBundling/2.0.2

Cheers for logging the bug! Another reason to use my package as that regex was straight out of the original library.

**Comment by mrbelk** [comment]
awesome.  thanks for such a quick turnaround on this.

**Comment by benmccallum** [comment]
No worries. You caught me just before I went to bed. 12:15am here now in Aus haha. All the best.

**Comment by mrbelk** [comment]
perfect timing, then. nighty night.
